"use client";

import Image from 'next/image'
import './globals.css'
import { Inter } from 'next/font/google'
import { Container } from '@src/components/container'
import { usePathname } from 'next/navigation'
import { NavLink } from '@src/components/nav/navlink';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header
					className="fixed top-0 w-full h-16 z-10 overflow-hidden border-b border-solid border-neutral-700 bg-opacity-60 backdrop-blurry">
					<Container size='nav'>
						<nav className='flex items-center h-16 gap-12 text-sm'>
							<a href='/'>
								<Image src={"MyProfilePicFullNoBack.svg"} alt={"Rafaeltab"} width={140} height={140} />
							</a>
							<div id='nav-links' className='flex gap-6 text-neutral-500'>
								<NavLink href="/tech" title="Tech" />
								<NavLink href="/projects" title="Projects" />
								<NavLink href="/timeline" title="Timeline" />
							</div>
						</nav>
					</Container>
				</header>

				<main className="h-screen overflow-y-scroll">
					{children}
				</main>

			</body>
		</html>
	)
}
