export const tech = {
  databases: [
    "CockroachDB",
    "PostgreSQL",
    "MSSQL",
    "MySQL",
    "Redis",
    "Influx",
    "SQLite",
    "KurrentDB",
    "Prometheus",
    "Elasticsearch",
    "Azure Storage Accounts",
  ],
  csp: [
    "Heroku",
    "AWS",
    "Azure",
    "Linode",
    "GCP",
    "Oracle Cloud Infrastructure",
    "Vercel",
  ],
  frameworks: [
    "Axum",
    "Actix",
    "ExpressJS",
    "NestJs",
    "ASP.NET",
    "NextJS",
    "ViteJS",
    "React",
    "Angular",
    "Flutter",
    "React Native",
    "Expo",
    "TailwindCSS",
    "Entity Framework",
    "Mocha",
    "Jest",
    "Vitest",
    "Flutter BLoC",
    "Riverpod",
    "jQuery",
    "NodeJS",
    "Unity",
    "RxJS",
    "IIS",
    "WPF",
  ],
  transports: [
    "HTTPS",
    "gRPC",
    "Kafka",
    "Redpanda",
    "NATS.IO",
    "Azure Service Bus",
    "WebSockets",
  ],
  tools: [
    "Prettier",
    "ESLint",
    "Pnpm",
    "Bun",
    "Npm",
    "Yarn",
    "Melos",
    "Turborepo",
  ],
  hosting: [
    "Kubernetes",
    "Docker",
    "cert-manager",
    "Open Telemetry",
    "Service Fabric",
    "Bare metal",
    "Grafana",
    "K3s",
    "Helm",
  ],
  devops: ["GitHub", "Azure DevOps", "Terraform", "Azure Bicep", "Pulumi"],
  patterns: [
    "Event sourcing",
    "Domain Driven Design",
    "Event Driven Architecture",
    "Hexagonal Architecture",
    "Clean Architecture",
    "Model-View-Controller",
    "Model-View-ViewModel",
  ],
};
